### ISSUE TITLE
Add human motion 3d Visualization

### ISSUE THREAD

**Issue by guptashekhar54** [tileb1/motion-prediction-tim#1]
Hello, I was reading your paper and I found it interesting. I like your work and your structured code. 
Can you add visualization code. 
How did you write MPJE in README?

Thank you

**Comment by tileb1** [comment]
Hi, thank you for your interest. If you run the training code as explained in the readme, it will generate as csv file with the MPJE error (defined in the paper where the sum over the time index doesn't apply) for each action and timestamp. Look at the jupyter notebook to see how it is averaged. I will include the visualization code when I have time, it needs some refactoring and that why I didn't add it initially.

Best,

Tim

**Comment by guptashekhar54** [comment]
Thanks for your response. I got how you calculate MPJE error. Please Add visualization code as you got free time. 
Thanks

**Comment by tileb1** [comment]
Hello, 
I added the visualization code, you can check how to call it in the readme!
Best,
Tim

**Comment by guptashekhar54** [comment]
Thanks for adding visualization file. I am having difficulty to understand H3.6M dataset. I read [this](http://vision.imar.ro/human3.6m/pami-h36m.pdf) paper. But I didn't understand much. Can you provide some source or give some intution to understand dataset. 

Thanks

**Comment by tileb1** [comment]
Hello, the dataset consists of .txt files for all actions performed by each subject. Consecutive lines represent consecutive time indices. 1 line corresponds to an exponential map encoding of a single skeleton at a given time index. [This function](https://github.com/tileb1/motion-prediction-tim/blob/e1df5b12d5b72f2698af32ce5f61ca814ba20f78/utils/data_utils.py#L577) will transform the exponential map to a 3D representation. This 3D representation is the concatenation of the 3D vectors of the 32 joints in the body.

**Comment by guptashekhar54** [comment]
Thanks for helping out.
