### ISSUE TITLE
How to get the visulization results?

### ISSUE THREAD

**Issue by LaLaLailalai** [tileb1/motion-prediction-tim#2]
Hi, I run the demo.py, but can't see the figure on the remote server, do you know how to deal with it? 
I try to save the figure and download it to my local computer, but failed due to the complex data.

**Comment by tileb1** [comment]
Hey, you can run demo.py locally with the pretrained model. If you want to train yourself, do so on the remote server, then fetch the saved model and run demo.py locally.
