### ISSUE TITLE
Does the future information leak into the model input?

### ISSUE THREAD

**Issue by thuyngch** [tileb1/motion-prediction-tim#3]
Hi author,
Thanks for your great work.

I am using the code, when reading the dataset, I find out that the input is sliced from the target along the joint dimension, not the temporal dimension.
In other words, the input is expected to contain only the past and present, but it also contains the future.
https://github.com/tileb1/motion-prediction-tim/blob/master/utils/h36motion3d.py#L37

Please help me to clarify this, thank you!

**Comment by tileb1** [comment]
Hi @thuyngch,
It might be confusing indeed but the model discards the future input in the forward pass. Please have a look here:
https://github.com/tileb1/motion-prediction-tim/blob/master/utils/model.py#L219

**Comment by thuyngch** [comment]
Ah I see, thanks for your clarification!
