### ISSUE TITLE
Code related to CMU dataset

### ISSUE THREAD

**Issue by gauraviiita** [tileb1/motion-prediction-tim#4]
Hello Authors,
Thanks for your great work.
I am seeing here you have written to upload codes for CMU dataset. But I am not seeing the code for that. Can you upload the code of your work for CMU dataset. 

Thank you

**Comment by tileb1** [comment]
Hi @gauraviiita,
Thanks for your message. I completely forgot about this and I don't have access to the code anymore so I won't be able to upload code related to the CMU dataset, sorry.
